### ISSUE TITLE
Add `status` field to each documentation pages

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/clear-linux-documentation#1164]
Currently, the documentation site displays the date of last update for the whole site at the end of the webpage.

I suggest to add a `status` field/section in the template, which is rendered and displayed somewhere near the top of the page (e.g. below title).

Specifically, the `status` field would be one of the following:

- `last updated on <DATE>` for normal docs
- `deprecated since <VERSION_NO|DATE>`, for contents no longer provided by official repository, or CL team decided not to update the docs any more
  - as an hypothetical example, tutorial on a desktop environment not included any more)

I believe it's very beneficial to multiple parties:

- If users found a docs was last updated very long ago, possibly they'd avoid wasting time debugging things caused by breaking version updates in softwares
  - I recently encountered a [report](https://community.clearlinux.org/t/openvino-tutorial-not-working/4457) in the forum that a certain tutorial no longer works. This could be common for Python packages, because they often relies on specific version of dependencies and the rolling release model doesn't work well (IMO).
- The `deprecated` docs would still be helpful to people running on an old version of Clear Linux, or on forks based on old CL. 
- Contributers made great efforts writing docs, deprecating instead of simply removing the docs shows respect to their works.
-  In addition, I found many tutorials are very well-written, even if they're no longer applicable to CL, they probably would help users on other distros too

**Comment by mvincerx** [comment]
We're reviewing this issue. FYI: We keep an archive of tutorials (no longer supported) here:
https://docs.01.org/clearlinux/latest/tutorials/index.html#archive

**Comment by mvincerx** [comment]
@lebensterben. I find your suggestion very interesting.  I understand well the challenge of managing dependencies, having experience--like many others--developing apps. However, managing documentation for a [rolling-release](https://docs.01.org/clearlinux/latest/about.html#what-is-cl) Linux distro means our team must test and validate use cases as they arise--against the latest clearlinux build.  We then rely on users--like you--to submit GH Issues if a guide/tutorial doesn't work as advertised. 

For our team to add a status field to individual documents (that reflected last validated date or deprecated date) would add significant overhead, which ultimately may or may not be beneficial to all users. Sure, it could benefit some users. But it would also require us to test some use cases that may be strictly associated with previous builds of clearlinux isos.  That, in turn, would require us to correlate clearlinux build (numbers) from the past against specific status dates of documents. 
Because we support a rolling release Linux distro, we specifically avoid referencing build numbers wherever possible.  Perhaps in a Linux distro that isn't as frequently updated as our own, this suggestion would be more practical. Regardless, I appreciate your suggestion.
