### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ShalokShalom** [clearlinux/clear-linux-documentation#1261]
Opening the issue here, despite that this may the not the ideal location. 

You link at an archived repo: 

![image](https://user-images.githubusercontent.com/6344099/219199096-ba049276-b56f-4a78-bec1-24bd0d043b55.png)

https://clearlinux.org/developer

You also fail to specify, what happened with the project. Is there a replacement?
One planned?

**Comment by Vinfall** [comment]
I also come across several broken link which I bookmarked as technically references before. While documentation links are broken now possibly due to [their transition from clearlinux.org to GitHub pages](https://community.clearlinux.org/t/clearlinux-org-move-upcoming/9010) (again?), the project is still actively updated and community forum has new posts every day.

**Comment by pixelgeek** [comment]
Yes, as Vinfall notes, we're in a transition period right now, and a there's a lot of broken links.  Once we get the clearlinux.org and documentation websites set up how we want, we'll start working through all the links and updating them as necessary.

**Comment by ShalokShalom** [comment]
There are webpages, who scrape through your whole page and list you all the broken links. 

https://www.deadlinkchecker.com/

**Comment by pixelgeek** [comment]
The fact that this training is no longer maintained has now been noted in that section.  
![image](https://github.com/clearlinux/clear-linux-documentation/assets/1402359/33f06ed3-6f05-4f65-94b4-fddd06ca7176)

There are no plans to update it, however the basic information there is still informative and generally still useful.
