### ISSUE TITLE
How to install Clear Linux on Hyper-V using ISO

### ISSUE THREAD

**Issue by mkhalkidrissi** [clearlinux/clear-linux-documentation#191]
Hi,

I am looking to install a fresh Hyper-V VM using ISO, IMG or anything which will allow me to have more control on how I want to set up Clear Linux. Just like the manual installation in Bare metal, but for Hyper-V.
I tried using the ISO to run the installation but failed (I used same VM settings used for the official Hyper-V VM: Generation 2, disable secured boot...)

Any help about how to install fresh Clear Linux on Hyper-V will be appreciated.

Notes:
1- I have successfully tried "Use Hyper-V" VM, It is working as expected, but would like to change the partitioning and add more space to disk.
2- I have successfully used "Increase Clear Linux image virtual disk size" as well. 

Thanks,
Drissi

**Comment by puneetse** [comment]
What changes in particular are you wanting to make at install-time that you can't with the Hyper-V image?

Since Clear Linux is a [stateless](https://clearlinux.org/features/stateless) system, you could use the Hyper-V image, make the desired changes (to partitions or otherwise), and delete `\etc` and `\var` for the same net effect.

**Comment by mkhalkidrissi** [comment]
I was trying to reconfigure the Hyper-V image in a way to have /boot, /usr and /(root) on SSD and the other /var, /tmp, swap on HDD.
Could you please help me with the instructions to reconfigure the VM in this way?

**Comment by mkhalkidrissi** [comment]
Thank you for your help!
