### ISSUE TITLE
gifs on tutorials

### ISSUE THREAD

**Issue by mrkz** [clearlinux/clear-linux-documentation#226]
Are `*.gif` files allowed for tutorial pages on clearlinux site?

I would like to record a small gif for showing up some steps instead of just plain `*.png` images, but if `*.gif` files are not allowed/supported, I could use the images as well.

![gif_example](https://user-images.githubusercontent.com/978752/45232409-eadc2500-b294-11e8-8369-3e8f34e08904.gif)

**Comment by cmarcelo** [comment]
See also https://github.com/nbedos/termtosvg. Not applicable to all cases, but for terminal commands it might be a good idea.

**Comment by mrkz** [comment]
@cmarcelo thanks for the idea! For sure I'll take a look when I need terminal commands recordings. 

The reason for asking is basically so I can share the gif as a step-by-step representation of a tutorial,
this is the PR with the changes: https://github.com/clearlinux/clear-linux-documentation/pull/232

**Comment by mvincerx** [comment]
https://github.com/clearlinux/clear-linux-documentation/pull/232 has been merged.

**Comment by krisdale** [comment]
Follow up to the original question: 

Images are supported in the documentation (The collaboration guidelines recommend PNG or JPEG for screenshots: https://clearlinux.org/documentation/clear-linux/reference/collaboration/documentation/images). 

Since the documentation is generally instructional, we recommend against use of animated gifs to show how to do something, as the user cannot control the playback/speed. Instead, use step-wise instructions with supporting screenshots where it helps clarify the instructions. This is less work for the user to determine what steps are needed and more consistent with other CL documentation content.
