### ISSUE TITLE
Document the setup of proxy.

### ISSUE THREAD

**Issue by asifhg** [clearlinux/clear-linux-documentation#470]
There is no documentation on clearlinux.org that describes how to setup up proxy.

**Comment by phmccarty** [comment]
There is an autoproxy guide, but not a general proxy guide that I am aware of.

https://clearlinux.org/documentation/clear-linux/guides/clearlinux/autoproxy

**Comment by intelkevinputnam** [comment]
@tpleavitt , @ahkok Are there particular applications that we should add to this guide? Setting up environment variables for http etc is easy enough. I imagine setting up git to work with ssh is another useful thing to have. Is there anything else that "has" to be there?

**Comment by tpleavitt** [comment]
@intelkevinputnam , when I set up a new system I add the proxy info for the gnome shell in settings and also for firefox specifically as well as add my proxy variables in my .bashrc file.  Once the generic socks proxy is available we need to add instructions for that as well

**Comment by ahkok** [comment]
I'd like it to approach at least the following angles:

- configure the proxy for a system service (e.g. docker, but also any generic daemon that uses env vars)
- configure the proxy for all shells and programs in a desktop session
- redsocks setup
- how pacrunner works and what programs can use it
- gnome desktop proxy settings (does it even work?)
- git over ssh

essentially, we should try and cover as many possible angles so that people understand that there are lots of options available to them.

**Comment by bd-dean** [comment]
We should also show how to manage moving in and out of proxied networks -- how to both set and unset proxies for people who are mobile users.

**Comment by intelkevinputnam** [comment]
@bd-dean Do you have any BKMs for this?

**Comment by bd-dean** [comment]
I have a script snippet I add to .bashrc or /etc/profile that determines if the system is in the corporate network and sets proxy if so. This works for terminal/CLI use, which is my most frequent useage.

**Comment by intelkevinputnam** [comment]
@bd-dean I'll take it! Can you send me a copy?

**Comment by intelkevinputnam** [comment]
@ahkok I haven't used redsocks before. What's the best resource to start with?

**Comment by intelkevinputnam** [comment]
@ahkok , @tpleavitt @bd-dean @phmccarty 

I've started a PR for this issue. Please take a look: https://github.com/clearlinux/clear-linux-documentation/pull/514
