### ISSUE TITLE
Mixin feature may be being deprecated?

### ISSUE THREAD

**Issue by pixelgeek** [clearlinux/clear-linux-documentation#478]
Per Auke - Mixin may be being deprecated.  We may need to update our documentation.  

https://community.clearlinux.org/t/cant-add-rpm-package-to-bundle-with-mixin/143/8

May need to remove or add "deprecated" warnings to https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixin (and other places????) or update instructions or provide alternatives.

**Comment by mvincerx** [comment]
@MCamp859, please take this. Thanks.

**Comment by mvincerx** [comment]
@pixelgeek. Status?

**Comment by krisdale** [comment]
Mixin confirmed to be deprecated. No longer supported.

**Comment by mvincerx** [comment]
Per @pixelgeek, `mixin` removed from CL documentation.

**Comment by pixelgeek** [comment]
Please add a warning at the top of https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixin for those getting to that page via a google search.

**Comment by mvincerx** [comment]
I'm filing a ticket internally because this is a Drupal node error, not a documentation error. 
Note: 
I add a note regarding  deprecation of `mixin` here: https://clearlinux.org/documentation/clear-linux/guides
I removed the file `mixin` in GH-506. Read the [PR diff](https://github.com/clearlinux/clear-linux-documentation/commit/4b00a981d70b4d973b50891a441b57f227c0612d) to the very bottom.

**Comment by mvincerx** [comment]
Ticket closed this morning. Closing this issue. See my email.
