### ISSUE TITLE
Recommend adding a "Note" at the top of the Nvidia driver installation document stating this is a one-off approach...

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clear-linux-documentation#482]
to installing software on Clear.  It's not managed by swupd.  The nvidia driver is not updated with normal Clear updates.  And that it can possibly the existing Clear installation.  And that a swupd verify fix would eliminate it (as you already noted).

https://clearlinux.org/documentation/clear-linux/tutorials/nvidia

**Comment by puneetse** [comment]
I've added a note in this PR https://github.com/clearlinux/clear-linux-documentation/pull/474 to make the implications of manual installation more obvious. 

> And that it can possibly the existing Clear installation.

I'm not sure what you mean here but the PR above aims to isolate the nvidia installation and solve a lot of the conflicts. 

I wouldn't use the phrase "one-off approach" since DKMS makes it sustainable between CL updates.

**Comment by bktan8** [comment]
Thanks for making me aware of the new PR.  I stand corrected now.

**Comment by mvincerx** [comment]
Closing per merge of GH-474.
