### ISSUE TITLE
Mixer documentation around certificates

### ISSUE THREAD

**Issue by iphutch** [clearlinux/clear-linux-documentation#507]
Input to extend/improve mixer documentation:
https://github.com/clearlinux/mixer-tools/issues/579 

Could extend "how it works" documentation for this particular issue or influence docs on how to use mixer. Rchiossi also pointed out on IRC that descriptions on mixers basic use  such as how to remove bundles would also be beneficial.
https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer

**Comment by tpleavitt** [comment]
@rchiossi , can you describe the components that are missing so we can add to a trouble-shooting section in the mixer doc

**Comment by rchiossi** [comment]
I reviewed what we have and I believe the problem with mixer documentation is that we explain to our users how to create a new mix, but we stop there. There are a couple things that are essential to mixer operation that should be included:

- Explain **how to maintain** a downstream mix.
-- How to keep up to date with upstream
-- What is the difference between deleting a bundle and deleting the bundle content
-- What is a format bump and what we need it for
-- How to go through an upstream format bump
-- How to do a downstream format bump and when is it required
- Make it clear **when** should the user create a custom mix. I see many users using mixer when they should instead be user clr-installer to create a custom image.
- Explain what is the difference between the mix content and the image content created from that mix.

It would also be nice if we could have the information already available on the clear page organized into smaller chunks rather than having everything in a single page, specially considering that there is still a lot that needs to be added.

**Comment by mvincerx** [comment]
@bktan8 please review. @mvincerx meet and define overlap with architect the lifecycle. 
@krisdale FYI.

**Comment by mvincerx** [comment]
See also Deploy at scale for some more material. @puneetse

**Comment by mvincerx** [comment]
> I reviewed what we have and I believe the problem with mixer documentation is that we explain to our users how to create a new mix, but we stop there. There are a couple things that are essential to mixer operation that should be included:
> 
> * Explain **how to maintain** a downstream mix.
>   -- How to keep up to date with upstream 
NYS - Revise/add to [architect-lifecycle](https://clearlinux.org/documentation/clear-linux/guides/maintenance/architect-lifecycle), phase II. @mvincerx to do with @mbelluzzo  

>   -- What is the difference between deleting a bundle and deleting the bundle content
DONE - See: `mixer bundle add editors`, `mixer bundle edit editors` woven into revised [mixer](https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer).

>   -- What is a format bump and what we need it for
DONE - See: `A format bump is required when...` in [mixer](https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer).

>   -- How to go through an upstream format bump
NYS - Revise/add to architect-lifecycle, phase II. @mvincerx to do with @mbelluzzo
>   -- How to do a downstream format bump and when is it required
DONE - See: `A format bump is required when...` in [mixer](https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer).

> * Make it clear **when** should the user create a custom mix. I see many users using mixer when they should instead be user clr-installer to create a custom image.
NYS - TCS will combine content of [mixer-about](https://clearlinux.org/documentation/clear-linux/concepts/mixer-about) with [mixer ](https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer). This revision should explain the use-case need in more detail. 

> * Explain what is the difference between the mix content and the image content created from that mix.
NYS - Revise/add to [architect-lifecycle](https://clearlinux.org/documentation/clear-linux/guides/maintenance/architect-lifecycle), phase II. @mvincerx to do with @mbelluzzo
 
> It would also be nice if we could have the information already available on the clear page organized into smaller chunks rather than having everything in a single page, specially considering that there is still a lot that needs to be added.
We can address simplification when we combine the content, as noted above. 

I'm referencing your specific request line by line. 
NYS = Not Yet Started.

**Comment by rchiossi** [comment]
Hi Michael, a few comments on the tasks:

>> -- What is the difference between deleting a bundle and deleting the bundle content

> DONE - See: mixer bundle add editors, mixer bundle edit editors woven into revised mixer.

There is a misconception here. Actually, the confusion you made is exactly what I believe is happening to our users due to lack of proper documentation, so let me elaborate.

What is described in the docs right now if how to delete **bundle FILES** and how to edit the content of **bundle FILES**. I'm talking about how to delete **BUNDLES** and how to delete content of **BUNDLES**.

A **bundle file** is just a description used by mixer during build time to generate a bundle in the final mix. Unlike a bundle file which is composed of a single text file, a **bundle** has two major components: A manifest file that describes its contents and the content itself, which are the files installed in the user system.

Once a bundle is part of a mix, deleting its corresponding bundle file IS NOT (the emphasis on the not here!) how you delete the bundle from the mix. Actually, once a bundle is on the mix, if a user calls `mixer bundle delete` on that bundle file, it will leave the mix in a corrupted state and ghost files will be left in the user's machine. The proper procedure in this situation is to mark the bundle file as deprecated and remove it during a format bump. Note here that this is only requited to remove the bundle from being tracked by swupd. It is possible to remove the content of the bundle without removing its tracking, and that is what I mean by "deleting bundle content".

The content of a bundle can be removed with any normal mix, while removing the bundle tracking can only be done during format bumps. A release will usually wait until multiple bundles had their content deleted before doing a bump to clean up their tracking.
 
To delete the content of a bundle, we either remove the content of the bundle file or change it so it is composed of packages that are guaranteed to exist in the user system (e.g. the filesystem package). 

It is also important to note that the  'mixer bundle delete' command should only be used to delete bundle files that have never been part of build (e.g. if the user added a bundle with the wrong name or added a bundle by mistake before building).

>> -- What is a format bump and what we need it for

> DONE - See: A format bump is required when... in mixer.

The problem in this section is that it explains why a format bump is done for upstream, but it does not tell the user why they might need to do it themselves (like for deleting bundles, as described above). It also doesn't really explain what a format bump is, only what it is trying to achieve. I'll share a document with you with a proper explanation of the format bump process. It would be nice to have something similar available as part of our documentation.

>> -- How to do a downstream format bump and when is it required

> DONE - See: A format bump is required when...

This section does not explain how to do a bump. There is no mention to`mixer build upstream-format` command (which performs a downstream format bump when the user is trying to cross an upstream format bump), nor to our reference script `afb.sh` that should be used by the user when they are doing a downstream-only format bump or if they need more control over what happens during an upstream bump.
