### ISSUE TITLE
Telemetry page includes a command that no longer works

### ISSUE THREAD

**Issue by pixelgeek** [clearlinux/clear-linux-documentation#558]
At the bottom of the page https://clearlinux.org/documentation/clear-linux/guides/telemetrics/telemetry-config#telemetry-config

sudo mkdir -p /etc/telemetrics
sudo echo "unique machine ID" > /etc/telemetrics/opt-in-static-machine-id 
results in a 
-bash: /etc/telemetrics/opt-in-static-machine-id: Permission denied

**Environment (please complete the following):**
 - Clear Linux OS version: 30010
 
running 'su -s' and then echo from a # prompt worked.

**Comment by tpleavitt** [comment]
@bwarden , this command used to work and now doesn't.  If I do a `sudo su` and then run the command as root it works fine.  Is there something that changed that would cause this original command to stop working?

**Comment by bwarden** [comment]
> @bwarden , this command used to work and now doesn't. If I do a `sudo su` and then run the command as root it works fine. Is there something that changed that would cause this original command to stop working?

The shell redirect works as the owner of the shell; it happens before the sudo. This would only have worked before if you were already root, or if you otherwise had write permission to the directory.

Can be reworked as:
`echo "unique machine ID" | sudo tee /etc/telemetrics/opt-in-static-machine-id`
or more obscure overall, but starting with sudo for less copy/paste confusion:
`sudo tee /etc/telemetrics/opt-in-static-machine-id <<< "unique machine ID" > /dev/null`

**Comment by bwarden** [comment]
I stole the second version from @miguelinux; he might have even more exciting suggestions :)

**Comment by tpleavitt** [comment]
@bwarden , thanks!  I'll use the first one you listed since it is straight-forward.

**Comment by tpleavitt** [comment]
@bd-dean , when you add the section back to the telemetry guide for configuring the static machine id would you change the command for creating the opt-in-static-machine-id file to:
$ echo "unique machine ID" | sudo tee /etc/telemetrics/opt-in-static-machine-id
