### ISSUE TITLE
Error 404 for new doc entries

### ISSUE THREAD

**Issue by biapalmeiro** [clearlinux/clear-linux-documentation#581]
Page not found for the links below:
https://clearlinux.org/documentation/clear-linux/guides/maintenance/cpu-performance
https://clearlinux.org/documentation/clear-linux/tutorials/tutorial-proxy

**Comment by mvincerx** [comment]
I filed issues on these this morning. I will monitor the progress and update you here.

**Comment by ghindman** [comment]
https://clearlinux.org/features/telemetry is also dead

**Comment by biapalmeiro** [comment]
@ghindman Please, foloow this link for telemetry info:
[https://clearlinux.org/documentation/clear-linux/concepts/telemetry-about](url)

**Comment by ghindman** [comment]
Found that, yes, thanks - was just reporting the dead page.

**Comment by biapalmeiro** [comment]
Thanks

**Comment by mvincerx** [comment]
> https://clearlinux.org/features/telemetry is also dead
Thanks for bring it up, @ghindman. The above is not a dead. Instead we moved that content here: https://clearlinux.org/documentation/clear-linux/guides/telemetrics/telem-guide

You may notice several `feature` sections from our old website (<May 2019) are now integrated into our guides with our new site, like with telem-guide.  

You may receive a 404 because we have internally reorganized some sections. Thanks for your patience while we work out the kinks. :)

**Comment by mvincerx** [comment]
> Page not found for the links below:
> https://clearlinux.org/documentation/clear-linux/guides/maintenance/cpu-performance
> https://clearlinux.org/documentation/clear-linux/tutorials/tutorial-proxy

Above two pages are now restored. Again, thanks for your patience as we work through this.
