### ISSUE TITLE
Document about performance

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#801]
**Do you think Clear Linux documentation needs a new document? Please describe.**
It has been pointed out that by @pixelgeek and others that documentation describing how CL aims for performance in more detail would be nice to reference. 

Right now there is just one section on https://clearlinux.org/about that doesn't go into much detail.

**Should the new document be a guide, a reference, or a tutorial?**
Recommend a type of document, based on the structure here: About or Reference maybe

**Comment by mvincerx** [comment]
@krisdale will work with @puneetse

**Comment by lavacano** [comment]
You've appealed to a community... well this explains it https://www.shlomifish.org/humour/by-others/funroll-loops/Gentoo-is-Rice.html .  Since Michael Larabel @michaellarabel seemingly loves your distro and phoronix IS the news site everyone checks it'd be nice to see some 3rd party graphs and as you saw from the -funroll-infinite-loops site we love seeing gcc flags.  Graphs and flags.  :+1:

**Comment by mvincerx** [comment]
In progress.

**Comment by mvincerx** [comment]
@puneetse Please review comments from @krisdale

**Comment by mvincerx** [comment]
@krisdale working with @puneetse to convert to reST. 
Reviewers: @ahkok and @bryteise
