### ISSUE TITLE
Bugs in Nvidia Documentation

### ISSUE THREAD

**Issue by 0xA1B2** [clearlinux/clear-linux-documentation#831]
Hello,

this document has some errors and is incomplete:

https://docs.01.org/clearlinux/latest/tutorials/nvidia.html

Add:
Check for latest Nvidia drivers here:
https://www.nvidia.com/en-us/drivers/unix/

Add:
Many systems come with an Intel CPU-GPU. The driver for that usually needs to be disabled so that the Nvidia driver works (alone). The documentation needs to explain that, and how to disable the Intel GPU driver, like i915 or newer

Fix:
sudo swupd repair --quick --bundles=lib-opengl

That command currently does not work. 

This works:

sudo swupd verify --quick --fix --bundles=lib-opengl

Add:
Older Lenovo notebooks like T520, W520 etc. need to disable Optimus in the BIOS and set to use the discrete GPU only. Disable Optimus detection, too. But thats not enuff, also all virtualization extensions need to be disabled (VT-d etc.). Those are in two different locations in the BIOS and both need to be disabled.

Just to clarify, the Nvidia+VT bug applies only to older Lenovo models, ca. up to T530 series before Haswell gen.

Add:
There is a nvidia-settings.desktop file if you search with nautilus, add that file to the usual GNOME application folder to get the nvidia-settings icon for quick access.

Bug:
Screen dimming (backlight control - not brightness) on the notebook screen does not work with the Fn-Keys. nvidia-settings only allows brightness control, not backlight intensity.

Praise:
CL is the only system where the Nvidia 390.129 driver actually works on a T520. FreeBSD 12 and Debian 10 failed badly with various compiler errors.

**Comment by mvincerx** [comment]
@puneetse, could you review this?

**Comment by 0xA1B2** [comment]
Fixed Backlight control which applies to various Nvidia chips in older notebooks:

sudo gedit /usr/share/X11/xorg.conf.d/10-nvidia-brightness.conf

Section "Device"
Identifier "Device0"
Driver "nvidia"
VendorName "NVIDIA Corporation"
BoardName "NVS 4200M"
Option "RegistryDwords" "EnableBrightnessControl=1"
EndSection

reboot

**Comment by puneetse** [comment]
> Add:
> Check for latest Nvidia drivers here:
> https://www.nvidia.com/en-us/drivers/unix/

Nice, I didn't know about this link. I'll add it as an alternative/reference. I prefer the dowloads divers page as the primary link for users who don't necessarily know what they're looking for yet.


> Add:
> Many systems come with an Intel CPU-GPU. The driver for that usually needs to be disabled so that the Nvidia driver works (alone). The documentation needs to explain that, and how to disable the Intel GPU driver, like i915 or newer

Agreed. Systems with NVIDIA Optimus have another level of complexity and keep coming up so a note about them is in order. 



> Fix:
> sudo swupd repair --quick --bundles=lib-opengl
> 
> That command currently does not work.
> 
> This works:
> 
> sudo swupd verify --quick --fix --bundles=lib-opengl

Ugh. Yes. Thanks.

> Add:
> Older Lenovo notebooks like T520, W520 etc. need to disable Optimus in the BIOS and set to use the discrete GPU only. Disable Optimus detection, too. But thats not enuff, also all virtualization extensions need to be disabled (VT-d etc.). Those are in two different locations in the BIOS and both need to be disabled.
> 
> Just to clarify, the Nvidia+VT bug applies only to older Lenovo models, ca. up to T530 series before Haswell gen.

I rather not get into the business of including the quirks of individual platforms unless they are wider issues. It's not that they aren't important, it's that there are so many that it can get out of hand quickly and distract from the original content for the larger audience. 

Also, those problems tend to not be unique to Clear Linux and already discussed in better detail elsewhere on the Internet. I think a better approach to this would be to offer links to those existing discussions. 

> Add:
> There is a nvidia-settings.desktop file if you search with nautilus, add that file to the usual GNOME application folder to get the nvidia-settings icon for quick access.

Good idea. At first I was concerned it couldn't be simply copied because the version in source is meant for projects that package nvidia-settings and can replace the values at buildtime. But it looks like the nvidia-installer or some other wrapper automatically includes the right paths based on the installpath. 

An alternative would be adding `/opt/nvidia/share` to `$XDG_DATA_DIRS`.


> Bug:
> Screen dimming (backlight control - not brightness) on the notebook screen does not work with the Fn-Keys. nvidia-settings only allows brightness control, not backlight intensity.

Let's provide a link to this since it is limited in audience and not Clear Linux specific.
