### ISSUE TITLE
Document how to use the enterprise-login tools with Clear

### ISSUE THREAD

**Issue by tpleavitt** [clearlinux/clear-linux-documentation#866]
**Do you think Clear Linux documentation needs a new document? Please describe.**
Document and demonstrate how to use several of the tools available in the enterprise-login bundle.

**Should the new document be a guide, a reference, or a tutorial?**
Guide

**Describe or provide examples of similar documents, if possible, from other web sites**
Internal docs

**Additional context**
Request originated from the Clear Linux forums: https://community.clearlinux.org/t/enterprise-login-bundle/1897

**Comment by mvincerx** [comment]
For more details on contents of bundle, see: 
https://github.com/clearlinux/clr-bundles/blob/master/bundles/enterprise-login

**Comment by tpleavitt** [comment]
Closing for now, will revisit if more interest shown from community

**Comment by jennydaman** [comment]
Hi, this is an expression of some interest from the community.

I am trying to set up a Clear Linux server with PAM to authenticate login to local user accounts but using passwords from Active Directory. AD works, after setting up a simple `/etc/krb5.conf` I can successfully run `kinit`.

I am very confused about how to use "enterprise-login," I am not sure exactly which packages are included. To accomplish AD authentication, it looks like I should be using sss (opposed to winbind or pam-krb5) because the bundle provides  `pam_sss.so`

```
$ sudo swupd bundle-info --files enterprise-login | grep pam_
 - /usr/lib64/security/pam_sss.so
```

However, **the bundle `enterprise-login` does not provide a systemd unit file for sssd daemon**. Following the general documentation and documentation for RHEL about _sss_ does not work. Clearly, enterprise-login works differently on Clear Linux than its respective packages do on other distros. Unfortunately this is still undocumented.

Trying to run `sssctl config-check`

```
$ sudo sssctl config-check
Issues identified by validators: 0

Messages generated during configuration merging: 1
Directory /etc/sssd/conf.d does not exist.

Used configuration snippet files: 0
```

But every other sss* command fails.

```
$ sudo sssctl user-checks [REDACTED]
(2020-08-03 20:05:24:048976): [sssd] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
(2020-08-03 20:05:24:049052): [sssd] [confdb_setup] (0x0010): The confdb initialization failed [5]: Input/output error
(2020-08-03 20:05:24:049082): [sssd] [sss_tool_confdb_init] (0x0010): Unable to setup ConfDB [5]: Input/output error
(2020-08-03 20:05:24:049100): [sssd] [sss_tool_route] (0x0010): Command initialization failed [5] Input/output error
$ sudo sssctl domain-list
(2020-08-03 20:06:58:960174): [sssd] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
(2020-08-03 20:06:58:960250): [sssd] [confdb_setup] (0x0010): The confdb initialization failed [5]: Input/output error
(2020-08-03 20:06:58:960268): [sssd] [sss_tool_confdb_init] (0x0010): Unable to setup ConfDB [5]: Input/output error
(2020-08-03 20:06:58:960290): [sssd] [sss_tool_route] (0x0010): Command initialization failed [5] Input/output error
$ sudo sssd
(2020-08-03 20:07:34:737796): [sssd] [ldb] (0x0020): Unable to open tdb '/var/lib/sss/db/config.ldb': No such file or directory
(2020-08-03 20:07:34:737858): [sssd] [ldb] (0x0020): Failed to connect to '/var/lib/sss/db/config.ldb' with backend 'tdb': Unable to open tdb '/var/lib/sss/db/config.ldb': No such file or directory
(2020-08-03 20:07:34:737895): [sssd] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
(2020-08-03 20:07:34:737928): [sssd] [confdb_setup] (0x0010): The confdb initialization failed [5]: Input/output error
(2020-08-03 20:07:34:737945): [sssd] [load_configuration] (0x0010): Unable to setup ConfDB [5]: Input/output error
(2020-08-03 20:07:34:737966): [sssd] [main] (0x0020): SSSD couldn't load the configuration database.
```

**Comment by mvincerx** [comment]
I see the `ssd` is included in the `enterprise-login` bundle. 
View the packages included here: https://github.com/clearlinux/clr-bundles/blob/master/bundles/enterprise-login
@phmccarty, @miguelinux, Can one of you give any insight on whether `sss*` commands are supported or not?

**Comment by phmccarty** [comment]
@mvincerx We don't have any specific tests for `sssd`, but it was confirmed working a while ago (see https://github.com/clearlinux/distribution/issues/945).

**Comment by mvincerx** [comment]
@phmccarty Thanks for the follow up. 
@jennydaman Please review the discussion on the thread, linked above. Let us know if this helps.

**Comment by jennydaman** [comment]
That is a lot to flip through...

The linked issue was not fully resolved (still missing systemd scripts). Some parts were helpful in getting somewhere, now I have the same error

```
dbus[702]: arguments to dbus_server_get_address() were incorrect, assertion "server != NULL" failed in file dbus-server.c line 835.
This is normally a bug in some application using the D-Bus library.
   
   D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```

Though I have a very small use-case of SSS (at the moment). I found a workaround for my own goal, though I might revisit SSS in the future if I need any more features.

My workaround for authenticating users against Active Directory was to copy `/usr/share/pam.d/common-auth` to `/etc/pam.d/common-auth` and add

```
auth    sufficient                      pam_exec.so expose_authtok /usr/local/bin/kinit_wrapper.sh
```

`kinit_wrapper.sh` is pretty simple

```
sudo -u $PAM_USER /usr/bin/kinit
```

**Comment by retpoline** [comment]
> 
> `kinit_wrapper.sh` is pretty simple
> 
> ```
> sudo -u $PAM_USER /usr/bin/kinit
> ```

Please quote $PAM_USER because as-is this can allow for any remote user (without properly authenticating) to inject commands with root privileges.

> sudo -u "$PAM_USER" /usr/bin/kinit

Otherwise, well you can try it out.

```
ssh "root su -c whoami root"@server
password: [doesn't matter] 
Permission denied, please try again.
```

And if you specified log=/tmp/log.txt after expose_authtok in the common-auth line, you will see the results of the whoami command "root" in the log file.
