### ISSUE TITLE
Documentation - Create a bootable USB drive

### ISSUE THREAD

**Issue by froginperil** [clearlinux/clear-linux-documentation#968]
Unless I am mistaken of=/dev/sdx and not /dev/sdx1. The documentation is unclear. Moreover #lsblk -S is a better bet than just #lsblk  
[xxx@amphib Downloads]$ lsblk -S
NAME HCTL       TYPE VENDOR   MODEL             REV TRAN
sda  3:0:0:0    disk WD       My_Passport_0810 1049 usb
sdb  2:0:0:0    disk WD       My_Passport_25E2 4005 usb
sdc  4:0:0:0    disk PNY      USB_3.0_FD       PMAP usb

**Comment by puneetse** [comment]
@froginperil can you link the document you're looking at that is saying to dd the partition instead of disk?

**Comment by tpleavitt** [comment]
The initial intent of doing it this way was because we were copying an entire GPT image to the USB device, not just a specific partition

**Comment by mvincerx** [comment]
@froginperil, I reviewed your feedback, and your request is not clear to me. Please identify which step isn't clear and state why if applicable. You may be referring to Steps 5 and 6 under USB for Linux.

**Comment by froginperil** [comment]
Hi Michael:

I have been at this for a very long time (RH7.x). Be assured that I am just trying to help - not criticize.

Yes, this was creating a bootable USB stick from Linux at https://docs.01.org/clearlinux/latest/get-started/bootable-usb.html#bootable-usb-linux (which works perfectly by the way). What is unclear is this:

"sudo dd if=./clear-[version number]-live-[desktop | server].iso of=<your USB device> oflag=sync bs=4M status=progress"

In the previous panel, devices are identified with a simple lsblk. That produces /dev/sdx1, etc. Were someone to use that as the device identifier (eg /dev/sdc1) in the dd command I doubt that the thing would boot.

What I suggest is first using lsblk -S

Then changing the instruction to of=/dev/sdx.

Of course Linux idiots (and I have been one from time to time) are determined to create tragedy. That could include creating a large image file at /dev/sdx.

Kudus to the developers. This seems to be a very solid distro. After 20 years of yum then dnf, I am just trying to fully appreciate bundles. The idiot part of me is resistant ;-)

**Comment by tpleavitt** [comment]
Now I see what you're talking about.  That got changed some time in the past to `of=<your USB device>` and we didn't explain that that needs to the parent device, not one of the sub-devices...it is very unclear right now and thanks for bringing that to our attention!

**Comment by mvincerx** [comment]
Agreed. @froginperil How about submitting a PR? Here's how: 
https://docs.01.org/clearlinux/latest/collaboration/collaboration.html#contribute-via-github

**Comment by froginperil** [comment]
@mvincerx I'm working on it and have downloaded to files. Of course I might also have to re-write the instructions regarding github collaboration ;-)

**Comment by mvincerx** [comment]
I look forward to reviewing your PR. In short, it's not that the [current document](https://docs.01.org/clearlinux/latest/get-started/bootable-usb.html#bootable-usb-linux) is wrong; rather, the problem is that  this `<your USB device>` might be misconstrued. 

Let's suppose `<your USB device>`  is `/dev/sdd` -- per [current example](https://docs.01.org/clearlinux/latest/get-started/bootable-usb.html#bootable-usb).   

Someone could potentially (in error) use this command: 

`sudo dd if=./clear-[version number]-live-[desktop | server].iso of=/dev/sdd1 oflag=sync bs=4M status=progress`

.. whereas it should be: 

`sudo dd if=./clear-[version number]-live-[desktop | server].iso of=/dev/sdd oflag=sync bs=4M status=progress`

In this case, I recommend that this command in this document specifies `of=/dev/sdd`... to avoid confusion or misinterpretation. Revising this command will follow the example output that precedes it.
